feat: add validate branch name job to the pr ci workflow (#2)
* feat: add validate branch name job to the pr ci workflow

diff --git a/.github/workflows/pr-to-develop-ci.yml b/.github/workflows/pr-to-develop-ci.yml
--- a/.github/workflows/pr-to-develop-ci.yml
+++ b/.github/workflows/pr-to-develop-ci.yml
@@ -7,11 +7,27 @@ on:
     branches: [develop]
 
 jobs:
+  validate-branch-name:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Validate branch name
+        run: |
+          if [[ ${{ github.head_ref }} =~ ^(feature|bugfix|test)/.*$ ]]; then
+            echo "Branch name is valid"
+          else
+            echo "Invalid branch name. Please use 'feature/<name>', 'bugfix/<name>' or 'test/<name>' format"
+            exit 1
+          fi
+
   build:
+    needs: validate-branch-name
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
       - name: Use NodeJS v18.x
         uses: actions/setup-node@v3
         with:
@@ -19,7 +35,7 @@ jobs:
       - name: Install dependencies
         run: npm install
       - name: Start lint
-        run: npx nx affected --target=lint
+        run: npx nx affected --target=lint --base=origin/develop
       - name: Start build
         run: npx nx affected --target=build --base=origin/develop
       - name: Start Unit tests
