feat: add validate branch name job to the pr ci workflow

diff --git a/.github/workflows/pr-to-develop-ci.yml b/.github/workflows/pr-to-develop-ci.yml
--- a/.github/workflows/pr-to-develop-ci.yml
+++ b/.github/workflows/pr-to-develop-ci.yml
@@ -7,6 +7,19 @@ on:
     branches: [develop]
 
 jobs:
+  validate-branch-name:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Validate branch name
+        run: |
+          if [[${{ github.ref }} =~ ^refs/heads/(feature|bugfix|test)/.*$]]; then
+            echo "Branch name is valid"
+          else
+            echo "Invalid branch name. Please use 'feature/<name>', 'bugfix/<name>' or 'test/<name>' format"
+            exit 1
+          fi
+
   build:
     runs-on: ubuntu-latest
 
